### PR TITLE
Blog post for the June 2016 Webdev Extravaganza.

### PR DESCRIPTION
**Pull request by Osmose**
@stephaniehobson @hoosteeno @peterbe @erikrose @emceeaich @pmclanahan @casebenton r?

I'll be posting this on Wednesday morning, so please leave your feedback before then.

### CODE REVIEW

**Comment by hoosteeno** [comment]
LGTM, thanks!

**Comment by pmac** [comment]
r+ 🍰

**Comment by emceeaich** [comment]
+1

**Comment by peterbe** [comment]
👍

**Pull request merged**
