### PR TITLE
Beer and Tell blog post for April 2016.

### PR DESCRIPTION
**Pull request by Osmose**
@emceeaich @lmorchard @groovecoder @pomax r?

I'll be posting this on Thursday, so please leave any feedback before then.

@lmorchard: Can you share some links to the web tools you showed off during the keyboard segment? I couldn't really fill out that section without those links.

### CODE REVIEW

**Comment by groovecoder** [comment]
r+ thanks!

**Comment by emceeaich** [comment]
:shipit:

**Comment by Pomax** [comment]
whoa wait what we're on github now? also :gun: :ring: :wedding: from my end.

**Comment by Osmose** [comment]
@Pomax Is that an r+ because I don't speak teenager anymore

**Comment by Pomax** [comment]
it's a shotgun wedding, but the keys are right next to r+

**Comment by lmorchard** [comment]
Oh hey, this got lost in my inbox :disappointed: Some links to the tools I used for the keyboard:
- [Keyboard Layout Editor](http://www.keyboard-layout-editor.com/)
- [SwillKB plate & case builder](http://builder.swillkb.com/)

**Pull request merged**
