### PR TITLE
Extravaganza blog post for February 2016.

### PR DESCRIPTION
**Pull request by Osmose**
@bensternthal @jezdez @glogiotatidis @jpetto @alexgibson @erikrose r?

I'll be posting this by Friday morning so please leave feedback before then. Thanks!

### CODE REVIEW

**Comment by jpetto** [comment]
Looks good to me! :+1:

**Comment by alexgibson** [comment]
I approve, thanks @Osmose! :tada:

**Comment by glogiotatidis** [comment]
LGTM thanks @Osmose :earth_africa:

**Comment by jezdez** [comment]
Oh, sorry, missed that one. Belated :+1:

**Pull request merged**
